weightonearth = float(input("Enter your weight in kg: "))
weightonmoon = round(weightonearth *1.622/9.81, 1)
weightonmercury = round(weightonearth *3.7/9.81, 1)
weightonvenus = round(weightonearth * 8.87/9.81 ,1)
weightonmars = round(weightonearth*3.711/9.81, 1)
weightonjupiter = round(weightonearth*24.79/9.81, 1)
weightonsaturn = round(weightonearth*10.44/9.81, 1)
weightonuranus = round(weightonearth*8.69/9.81, 1)
weightonneptune = round(weightonearth*11.15/9.81, 1)

print("Your weight on Moon: ", weightonmoon,)
print("Your weight on Mercury: ",weightonmercury,)
print("Your weight on Venus: ",weightonvenus,)
print("Your weight on Mars: ",weightonmars,)
print("Your weight on Jupiter: ", weightonjupiter,)
print("Your weight on Saturn: ", weightonsaturn,)
print("Your weight on Uranus: ",weightonuranus,)
print("Your weight on Neptune: ",weightonneptune)